config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'demo#index'

  get '/articles_list', to: 'demo#articles_list'
  get '/articles_cache', to: 'demo#articles_cache'
  get '/articles_search', to: 'demo#articles_search'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

# rails g model Article
#  title:string
#  content_raw:text
#  content:text
#  status:string

# rake db:migrate
#
class Article < ApplicationRecord
  # ElasticSearch / Chewy
  update_index('articles') { self }

  # Validations
  validates :title, presence: true, length: { minimum: 3 }

  # Kaminari. Pagination
  paginates_per 3

  # Take a raw content from a user and save it in `content_raw`.
  # But never render `content_raw` on a page. It is dangerous!
  # Process a content once `on save` and cut off dangerous tags.
  # Now you can render `content` field on a page with using `raw` helper
  # <%= raw article.content %>
  before_save :prepare_content

  # https://www.ruby-toolbox.com/projects/sanitize
  def prepare_content
    self.title = Sanitize.fragment(title, { elements: [] }).strip
    self.content = Sanitize.fragment(content_raw, Sanitize::Config::RESTRICTED).strip
  end
end

app/models/currency_rate.rb
# frozen_string_literal: true

# rails g model currency_rate
#   from:string
#   to:string
#   rate:float

# rails runner CurrencyRate.get
# rails runner 'CurrencyRate.get("KGS", "USD")'
# rails runner "CurrencyRate.get('USD', 'EUR')"

class CurrencyRate < ApplicationRecord
  API = 'https://api.exchangerate.host/latest'

  def self.get(from = 'USD', to = 'EUR')
    uri = URI(CurrencyRate::API + "?base=#{from}&symbols=#{to}")

    response = Net::HTTP.get(uri)
    response_obj = JSON.parse(response)

    create!(
      from:, to:,
      rate: response_obj['rates'][to]
    )

    puts "[#{DateTime.now.strftime('%d.%m.%Y %H.%M.%S')}]: " \
         "#{from}:#{to} currency rate: " + response_obj['rates'][to].to_s
  end
end

app/models/user.rb
# frozen_string_literal: true

# rails generate devise user
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :confirmable,
         :rememberable,
         :recoverable,
         :trackable,
         :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/demo_controller.rb
# frozen_string_literal: true

class DemoController < ApplicationController
  before_action :get_articles, only: %w[index articles_list articles_cache]

  def index
    render 'articles/articles_list'
  end

  def articles_list
    render 'articles/articles_list'
  end

  def articles_cache
    render 'articles/articles_cache'
  end

  # Example of ElasticSearch/Chewy search
  def articles_search
    @term = params[:search] || 'Article'

    @articles = ArticlesIndex
                .query(
                  query_string: {
                    query: @term,
                    fields: %i[title content]
                  }
                )
                .per(3)
                .page params[:page]

    render 'articles/articles_search'
  end

  private

  # rubocop:disable Naming/AccessorMethodName
  def get_articles
    @articles = Article.order(:title).page params[:page]
  end
  # rubocop:enable Naming/AccessorMethodName
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/views/articles/_article.html.erb
<article class="article">
  <h3 class="article-header"><%= article.title %></h3>
  <p class="article-content"><%= raw article.content %></p>
</article>

app/views/articles/_cache_instruction.html.erb
<div class="section-description">
  <p>When caching is turned on this section should be rerendered only once per 1 minute.</p>
  <p>Currnetly cache is: <b><%= Rails.application.config.cache_store == :null_store ? "OFF" : "ON" %></b>.</p>
  <p>To toggle cache run in console: <b>bin/exec cache</b></p>
  <b>Rendered at</b> <%= DateTime.now.strftime('%d.%m.%Y %H.%M.%S') %>
</div>

app/views/articles/articles_cache.html.erb
<%= render partial: 'demo/common_info', locals: { file: __FILE__ } %>

<section>
  <h2 class="header-section">Articles. 1 minute caching</h2>

  <% cache("articles-1-minute-cache", expires_in: 1.minute) do %>
    <%= render partial: 'articles/cache_instruction' %>
    <% @articles.each do |article| %>
      <%= render partial: 'articles/article', locals: { article: article } %>
    <% end %>
  <% end %>
</section>

app/views/articles/articles_list.html.erb
<%= render partial: 'demo/common_info', locals: { file: __FILE__ } %>

<section>
  <h2 class="header-section">Articles. Without caching</h2>

  <div class="section-description">
    <p>Just a regular section with regular articles.</p>
    <p><b>Rendered at:</b> <%= DateTime.now.strftime('%d.%m.%Y %H.%M.%S') %></p>
  </div>

  <% @articles.each do |article| %>
    <%= render partial: 'articles/article', locals: { article: article } %>
  <% end %>

  <div class="section-pagination">
    <%= paginate @articles %>
  </div>
</section>

app/views/articles/articles_search.html.erb
<%= render partial: 'demo/common_info', locals: { file: __FILE__ } %>

<section>
  <h2 class="header-section">ElasticSearch results</h2>

  <div class="section-description">
    <p>Term/Displayed/Found: "<%= @term %>"/<%= @articles.size %>/<%= @articles.count %></p>
  </div>

  <% if @articles.size.zero? %>
    <div class="section-description">
      <p>Sorry. No Search Results</p>
    </div>
  <% end %>

  <% @articles.each do |article| %>
    <article class="article the-search-highlight" data-search-words="<%= [@term].to_json %>">
      <h3 class="article-header"><%= article.title %></h3>
      <p class="article-content"><%= raw article.content %></p>
    </article>
  <% end %>

  <div class="section-pagination">
    <%= paginate @articles %>
  </div>
</section>

app/views/demo/_common_info.html.erb
<%= content_for :common_info do %>
  <div class="header-warning">
    <b>Ruby version:</b> <%= `ruby -v` %><br>
    <b>Rails version:</b> <%= Rails.version %><br>
    We are in: <code><%= file.gsub(Rails.root.to_s, '') %></code>
    Controller &mdash; <b><%= controller.controller_name %></b>.
    Action &mdash; <b><%= controller.action_name %></b>.
  </div>
<% end %>

app/views/demo/_common_links.html.erb
<div class="examples">
  <%= link_to "Articles", articles_list_path, class: 'example-item' %>
  <%= link_to "Articles with Caching", articles_cache_path, class: 'example-item' %>
  <%= link_to "Elastic Search Example", articles_search_path, class: 'example-item' %>
</div>

app/views/demo/_footer.html.erb
<footer>
  Made with &hearts; by <a href="https://github.com/the-teacher">the-teacher</a>
</footer>

app/views/demo/_header.html.erb
<header>
  <div style="text-align:center">
    <h1 class="page-header">
      <a href="https://github.com/the-teacher/rails7-startkit#rails-7-start-kit">
        <img width="300px" src="/Rails7.StartKit.jpg" />
      </a>
    </h1>
    <p>
      <a href="https://github.com/the-teacher/rails7-startkit#rails-7-start-kit">Rails 7. StartKit.</a> Please tell your friends about this project.
    </p>
    <br>
  </div>

  <ul class="header-menu">
    <li class="header-item">
      <b>Root:</b>
      <%= link_to "Demo Index", "/" %>
    </li>

    <li class="header-item">
      <b>Mail Server:</b>
      <%= link_to "localhost:1080", "http://localhost:1080", target: :_blank %>
    </li>

    <li class="header-item">
      <b>ElasticSearch:</b>
      <%= link_to "localhost:9200", "http://localhost:9200", target: :_blank %>
    </li>

    <li class="header-item">
      <b>Devise:</b>
      <% if user_signed_in? %>
        <%= current_user.email %> |
        <%= link_to "Sign Out", destroy_user_session_path%>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %> |
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </li>
  </ul>
</header>

app/views/demo/index.html.erb
<%= render partial: 'demo/common_info', locals: { file: __FILE__ } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails7. StartKit. By Ilya N. Zykin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="body">
      <%= render partial: 'demo/header' %>
      <%= render partial: 'shared/flash_messages' %>
      <%= yield(:common_info) %>
      <%= render partial: 'demo/common_links' %>
      <%= yield %>
      <%= render partial: 'demo/footer' %>
    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="flash_message flash_message-<%= type %>">
    <%= msg %>
  </div>
<% end %>